swagger: '2.0'

info:
  title: AgentController2
  description: JumpScale Agent Controller 2
  version: 1.0.0  # This spec is actually not versioned

schemes:
  - https

basePath: /

produces:
  - application/json

paths:

  '/agents':
    get:
      summary: Lists the live agents
      responses:
        '200':
          description: The currently connected agents
          schema:
            type: array
            items:
              $ref: "#/definitions/AgentID"

  '/jobs':
    get:
      summary: Lists the scheduled jobs
      responses:
        '200':
          description: The scheduled jobs
          schema:
            type: array
            items:
              $ref: "#/definitions/ScheduledJob"

definitions:

  AgentID:
    properties:
      GID:
        type: integer
        format: (> 0)
      NID:
        type: integer
        format: unsigned

  Command:
    description: A command for an Agent (may have extra optional fields)
    properties:
      ID:
        type: string
      Gid:
        type: integer
      Nid:
        type: integer
      Cmd:
        type: string
      Roles:
        type: array
        items:
          type: string
      Fanout:
        type: boolean
      Data:
        type: string
      Tags:
        type: string

  ScheduledJob:
    properties:
      Cmd:
        $ref: "#/definitions/Command"
      ID:
        type: string
      Cron:
        type: string
        format: The schedule timing in Cron syntax