[main]
listen = ":8966"
redis_host =  "172.17.42.1:6379"
redis_password = ""

[influxdb]
host = "172.17.0.1:8086"
db   = "agentcontroller"
user = "ac"
password = "acctrl"

[handlers]
binary = "python2.7"
cwd = "./handlers"
env = ["PYTHONPATH=/opt/jumpscale7/lib:../client"]
