[main]
redis_host =  "127.0.0.1:6379"
redis_password = ""

#Default http
[[listen]]
  Address = ":8966"

#Example for https with multiple virtual hosts
#[[listen]]
#  Address = ":8443"
#  [[listen.tls]]
#    cert = "/path/to/domain1_certificate.cert"
#    key = "/path/to/domain1_keyfile.key"
#  [[listen.tls]]
#    cert = "/path/to/domain2_certificate.cert"
#    key = "/path/to/domain2_keyfile.key"

[influxdb]
host = "127.0.0.1:8086"
db   = "main"
user = "root"
password = "root"

[handlers]
binary = "python2.7"
cwd = "./handlers"
    [handlers.env]
    PYTHONPATH = "/opt/jumpscale7/lib"
    HOME = "/root"
    SYNCTHING_URL = "http://localhost:18384/"
    #SYNCTHING_API_KEY = ""
    REDIS_ADDRESS = "localhost"
    REDIS_PORT = "6379"
    #REDIS_PASSWORD = ""
